on: pull_request_review
name: Merge despues de aprobado
jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: taichi/approved-event-action@v1.2.6
      id: approved
      with:
        approvals: '1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "Approved !!"
      if: steps.approved.outputs.approved == 'true'
      
